# Generated by Django 4.2.1 on 2023-06-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('dept', models.CharField(max_length=15)),
                ('salary', models.IntegerField()),
                ('bonus', models.IntegerField()),
                ('role', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('Loan', models.AutoField(primary_key=True, serialize=False)),
                ('Gender', models.CharField(max_length=30)),
                ('Married', models.CharField(max_length=10)),
                ('Dependents', models.IntegerField()),
                ('Education', models.CharField(max_length=30)),
                ('Self_Employed', models.CharField(max_length=30)),
                ('ApplicantIncome', models.IntegerField()),
                ('CoapplicantIncome', models.IntegerField()),
                ('LoanAmount', models.IntegerField()),
                ('Loan_Amount_Term', models.IntegerField()),
                ('Credit_History', models.IntegerField()),
                ('Property_Area', models.CharField(max_length=20)),
                ('Loan_Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('userid', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
